[phases.setup]
nixPkgs = ["python3", "gcc", "gnumake", "nodejs_20"]

[phases.install]
cmds = ["npm install --include=optional --prefix api"]

[phases.build]
cmds = []

[start]
cmd = "node api/src/server.js"
