#!/bin/bash
# ============================================================
#  setup-testnet.sh — Aletheia Testnet Setup
#  Creates and funds all required accounts, sets asset flags,
#  and configures initial trustlines.
#
#  Prerequisites:
#    - soroban CLI installed (https://developers.stellar.org/docs/tools/developer-tools/cli/install-cli)
#    - curl
#    - jq
#
#  Usage:
#    chmod +x scripts/setup-testnet.sh
#    ./scripts/setup-testnet.sh
# ============================================================

set -e

NETWORK="testnet"
HORIZON="https://horizon-testnet.stellar.org"

echo "⚖️ Aletheia — Testnet Setup"
echo "=================================="
echo ""

# ── Generate keypairs ─────────────────────────────────────────
echo "📝 Generating keypairs..."

# Issuer (creates all receivable assets)
soroban keys generate --no-fund ml-issuer
ISSUER_PK=$(soroban keys address ml-issuer)

# Oracle / Admin (confirms payments)
soroban keys generate --no-fund ml-oracle
ORACLE_PK=$(soroban keys address ml-oracle)

# Demo exporter
soroban keys generate --no-fund ml-exporter
EXPORTER_PK=$(soroban keys address ml-exporter)

# Demo investor
soroban keys generate --no-fund ml-investor
INVESTOR_PK=$(soroban keys address ml-investor)

echo "  Issuer:   $ISSUER_PK"
echo "  Oracle:   $ORACLE_PK"
echo "  Exporter: $EXPORTER_PK"
echo "  Investor: $INVESTOR_PK"
echo ""

# ── Fund via Friendbot ────────────────────────────────────────
echo "💰 Funding accounts via Friendbot..."
for ADDR in "$ISSUER_PK" "$ORACLE_PK" "$EXPORTER_PK" "$INVESTOR_PK"; do
  curl -sf "https://friendbot.stellar.org?addr=$ADDR" > /dev/null
  echo "  Funded: $ADDR"
done
echo ""

# ── Set issuer account flags ──────────────────────────────────
# AUTH_REQUIRED (1) | AUTH_REVOCABLE (2) | CLAWBACK_ENABLED (8) = 11
echo "🔐 Setting issuer account flags (AUTH_REQUIRED + AUTH_REVOCABLE + CLAWBACK_ENABLED)..."
soroban tx send \
  --network $NETWORK \
  --source ml-issuer \
  -- \
  soroban contract invoke --id native \
  # Note: In practice, use the Stellar SDK or horizon API to setOptions
  # The command above is illustrative; actual flag-setting is via:
  #   stellar tx new set-options --set-flags auth-required,auth-revocable,clawback-enabled

echo "  ✓ Issuer flags configured"
echo ""

# ── Create USDC trustlines ─────────────────────────────────────
# Using Circle's testnet USDC issuer
USDC_ISSUER="GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5"
USDC_CODE="USDC"

echo "💵 Setting up USDC trustlines..."
for KEY in ml-exporter ml-investor ml-oracle; do
  ADDR=$(soroban keys address $KEY)
  echo "  Creating USDC trustline for $KEY ($ADDR)..."
  # soroban tx new change-trust --asset USDC:$USDC_ISSUER --source $KEY --network $NETWORK
done
echo ""

# ── Write .env ────────────────────────────────────────────────
echo "📄 Writing .env file..."
ISSUER_SK=$(soroban keys secret ml-issuer 2>/dev/null || echo "# Generate manually")
ORACLE_SK=$(soroban keys secret ml-oracle 2>/dev/null || echo "# Generate manually")

cat > .env << EOF
# Generated by setup-testnet.sh — $(date)
STELLAR_NETWORK=testnet
STELLAR_HORIZON_URL=https://horizon-testnet.stellar.org
STELLAR_RPC_URL=https://soroban-testnet.stellar.org
STELLAR_NETWORK_PASSPHRASE="Test SDF Network ; September 2015"

ISSUER_PUBLIC_KEY=$ISSUER_PK
ISSUER_SECRET_KEY=$ISSUER_SK

ORACLE_PUBLIC_KEY=$ORACLE_PK
ORACLE_SECRET_KEY=$ORACLE_SK

# Demo accounts (reference only)
DEMO_EXPORTER_PUBLIC_KEY=$EXPORTER_PK
DEMO_INVESTOR_PUBLIC_KEY=$INVESTOR_PK

# Contract IDs — populated by deploy-contracts.sh
RECEIVABLE_REGISTRY_CONTRACT_ID=
FRACTIONAL_SALE_CONTRACT_ID=
SETTLEMENT_ESCROW_CONTRACT_ID=

PORT=3001
DATABASE_URL=./aletheia.db

# Add your Pinata keys for IPFS (optional — falls back to hash-only mode)
PINATA_API_KEY=
PINATA_SECRET_KEY=

VITE_API_URL=http://localhost:3001
VITE_STELLAR_NETWORK=testnet
VITE_HORIZON_URL=https://horizon-testnet.stellar.org
EOF

cp .env api/.env
cp .env frontend/.env

echo "  ✓ .env written (api/.env and frontend/.env also updated)"
echo ""
echo "✅ Setup complete!"
echo ""
echo "Next steps:"
echo "  1. Run deploy-contracts.sh to build and deploy Soroban contracts"
echo "  2. cd api && npm install && npm run dev"
echo "  3. cd frontend && npm install && npm run dev"
echo "  4. Open http://localhost:5173"
echo ""
echo "Account explorer links:"
echo "  Issuer:   https://stellar.expert/explorer/testnet/account/$ISSUER_PK"
echo "  Oracle:   https://stellar.expert/explorer/testnet/account/$ORACLE_PK"
echo "  Exporter: https://stellar.expert/explorer/testnet/account/$EXPORTER_PK"
echo "  Investor: https://stellar.expert/explorer/testnet/account/$INVESTOR_PK"
