# setup-testnet.ps1 - Malabar Ledger Testnet Setup
# Creates and funds all required accounts on Stellar Testnet

param()

$ErrorActionPreference = 'Stop'

Write-Host "Malabar Ledger - Testnet Setup" -ForegroundColor Yellow
Write-Host "=================================="

# Ensure soroban is on PATH
$Env:Path = "$Env:Path;$HOME\.cargo\bin"

# ── Generate keypairs ──────────────────────────────────────────
Write-Host "Generating keypairs..." -ForegroundColor Cyan

soroban keys generate --overwrite ml-issuer
soroban keys generate --overwrite ml-oracle
soroban keys generate --overwrite ml-exporter
soroban keys generate --overwrite ml-investor

$ISSUER_PK   = (soroban keys address ml-issuer).Trim()
$ORACLE_PK   = (soroban keys address ml-oracle).Trim()
$EXPORTER_PK = (soroban keys address ml-exporter).Trim()
$INVESTOR_PK = (soroban keys address ml-investor).Trim()

$ISSUER_SK = (soroban keys secret ml-issuer).Trim()
$ORACLE_SK = (soroban keys secret ml-oracle).Trim()

Write-Host ("  Issuer:   " + $ISSUER_PK)
Write-Host ("  Oracle:   " + $ORACLE_PK)
Write-Host ("  Exporter: " + $EXPORTER_PK)
Write-Host ("  Investor: " + $INVESTOR_PK)

# ── Fund via Friendbot ─────────────────────────────────────────
Write-Host "Funding accounts via Friendbot..." -ForegroundColor Cyan

$accounts = @($ISSUER_PK, $ORACLE_PK, $EXPORTER_PK, $INVESTOR_PK)
foreach ($addr in $accounts) {
    try {
        $null = Invoke-RestMethod -Uri ("https://friendbot.stellar.org?addr=" + $addr) -Method Get
        Write-Host ("  Funded: " + $addr) -ForegroundColor Green
    }
    catch {
        Write-Warning ("  Failed to fund " + $addr + ". Fund it manually via https://laboratory.stellar.org/#account-creator?network=test")
    }
}

# ── Write .env files ───────────────────────────────────────────
Write-Host "Writing .env files..." -ForegroundColor Cyan

$lines = @(
    "# Generated by setup-testnet.ps1 on " + (Get-Date).ToString("yyyy-MM-dd HH:mm:ss"),
    "STELLAR_NETWORK=testnet",
    "STELLAR_HORIZON_URL=https://horizon-testnet.stellar.org",
    "STELLAR_RPC_URL=https://soroban-testnet.stellar.org",
    'STELLAR_NETWORK_PASSPHRASE=Test SDF Network ; September 2015',
    "",
    "ISSUER_PUBLIC_KEY=" + $ISSUER_PK,
    "ISSUER_SECRET_KEY=" + $ISSUER_SK,
    "",
    "ORACLE_PUBLIC_KEY=" + $ORACLE_PK,
    "ORACLE_SECRET_KEY=" + $ORACLE_SK,
    "",
    "# Demo accounts (reference only)",
    "DEMO_EXPORTER_PUBLIC_KEY=" + $EXPORTER_PK,
    "DEMO_INVESTOR_PUBLIC_KEY=" + $INVESTOR_PK,
    "",
    "# Contract IDs - populated by deploy-contracts.ps1",
    "RECEIVABLE_REGISTRY_CONTRACT_ID=",
    "FRACTIONAL_SALE_CONTRACT_ID=",
    "SETTLEMENT_ESCROW_CONTRACT_ID=",
    "",
    "PORT=3001",
    "DATABASE_URL=./malabar.db",
    "",
    "# Pinata keys (optional)",
    "PINATA_API_KEY=",
    "PINATA_SECRET_KEY=",
    "",
    "VITE_API_URL=http://localhost:3001",
    "VITE_STELLAR_NETWORK=testnet",
    "VITE_HORIZON_URL=https://horizon-testnet.stellar.org"
)

Set-Content -Path ".\.env"          -Value $lines
Set-Content -Path ".\api\.env"      -Value $lines
Set-Content -Path ".\frontend\.env" -Value $lines

Write-Host "  .env written (also api/.env and frontend/.env)" -ForegroundColor Green
Write-Host ""
Write-Host "Setup complete!" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:"
Write-Host "  1. Run .\scripts\deploy-contracts.ps1 to deploy Soroban contracts"
Write-Host "  2. cd api; npm install; npm run dev"
Write-Host "  3. cd frontend; npm install; npm run dev"
Write-Host ""
Write-Host "Account explorer links:"
Write-Host ("  Issuer:   https://stellar.expert/explorer/testnet/account/" + $ISSUER_PK)
Write-Host ("  Oracle:   https://stellar.expert/explorer/testnet/account/" + $ORACLE_PK)
Write-Host ("  Exporter: https://stellar.expert/explorer/testnet/account/" + $EXPORTER_PK)
Write-Host ("  Investor: https://stellar.expert/explorer/testnet/account/" + $INVESTOR_PK)